---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "gametes_generatemodels"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::gametes=2.1"
