name: "gametes_generatedatasets"

description: Complex SNP model simulations with gametes
keywords:
  - epistasis
  - datasets
  - SNP
tools:
  - "gametes":
      description: "Tool for the generation of complex single SNP models"
      homepage: "https://sourceforge.net/projects/gametes/"
      documentation: "https://sourceforge.net/projects/gametes/files/GAMETES_v2.1_Users_Guide.pdf"
      doi: "10.1186/1756-0381-5-16"
      licence: ["GPL v2"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'model1']`

  - model:
      type: file
      description: Text file reporting model parameters
      pattern: "*.{.txt}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - results:
      type: directory
      description: Folder containing the quantification results for a specific sample
      pattern: "${prefix}"

authors:
  - "@msantorsola"
maintainers:
  - "@msantorsola"
